logging:
  level:
    root: INFO

server:
  port: 8091
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    path: /documentation.html
    operationsSorter: method

spring:
  profiles:
    active: dev
#  banner:
#    charset: UTF-8
tenants:
  datasource:
    default-tenant:
        url: jdbc:mysql://localhost:3306/tenant1
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

#    location: classpath:/banner.txt
